project:
  type: website

website:
  title: "FFF Vårcup 2023"
  favicon: favicon-16x16.png
  navbar:
    logo: fff_logo_50pct.png
    right:
      - omkm2023.qmd
      - icon: github
        href: https://github.com/andreslagerlof/fffvc2023
  page-footer: 
    left: "FFF Vårcup 2023"
    right: "Sportcheferna FFF"
    background: light

format:
  html:
    theme: minty
    css: styles.css

editor: visual

